/*
 * File: app/store/CardStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.CardStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MyApp.model.Card'
    ],

    config: {
        model: 'MyApp.model.Card',
        storeId: 'CardStore',
        proxy: {
            type: 'syncstorage',
	    id: 'cards',
	    owner: 'user',
	    access: 'private'
        },
	remoteFilter: false,
	autoLoad: true,  //set auto load to true so that any local data will 
                         // populated in memory
        autoSync: false // Wait until we have an authenciated user to
                         // and call sync manually.
        
    }
});