/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({

});

Ext.application({
    io: {
        appId: '5217f781-3d3e-456a-ac24-bd415c41860d'
    },
    models: [
        'MyModel'
    ],
    stores: [
        'MyStore'
    ],
    views: [
        'MyList',
        'sioAuthButton'
    ],
    name: 'MyApp',
    controllers: [
        'MyController',
        'Ext.io.Controller'
    ],

    launch: function() {

        Ext.create('MyApp.view.MyList', {fullscreen: true});
    }

});
