/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',
    config: {
        models: [
            'Deck',
            'Card'
        ],
        stores: [
            'DeckStore',
            'CardStore'
        ],
        views: [
            'Main',
            'addCardSheet',
            'addDeckSheet'
        ]
    },
    /**
    *  When the controller is created it needs to 
    *  listen for events generated by Ext.io.Controller.
    */
    init: function() {
        this.getApplication().sio.on({
            authorized: this.onAuth,
            logout: this.onLogout,
            usermessage: this.onUserMessage,
            scope: this
        });
    },
       /**
    *  When the application has an authentcated user.
    */
    onAuth: function(user) {
        console.log("onAuth", user);
        Ext.getStore('DeckStore').sync();
        Ext.getStore('CardStore').sync();
        return true;
    },
    /**
    *  When the user gets a message from the application
    *  needs to call sync on the todo's store.
    */
    onUserMessage: function(sender, message) {
        var userId = sender.getUserId();
        console.log("user got a message!", arguments, userId);
        Ext.getStore('DeckStore').sync(function() {
            console.log("DeckStore sync callback", arguments);
        });
        Ext.getStore('CardStore').sync(function() {
            console.log("DeckStore sync callback", arguments);
        });
        return true;
    },

    /**
    * When the user logs out the application needs
    * to remove the local data from the store.
    */
    onLogout: function() {
        var deckStore = Ext.getStore('DeckStore');
        deckStore.getProxy().clear();
        deckStore.load();
        var cardStore = Ext.getStore('CardStore');
        cardStore.getProxy().clear();
        cardStore.load();
        return true;
    },

    /**
    * Add the task to the store from the value in a textfield.  
    * Call sync on the store to push changes to sencha.io
    * After sync completes call syncCallback.
    */
    addTodo: function(textfield, e, options) {
        console.log("addTodo");
        var todos = Ext.getStore('todos');
        todos.add({
            task: textfield.getValue(),
            completed: false,
            timestamp: new Date().getTime()
        });
        todos.sync(Ext.bind(this.syncCallback, this));
        textfield.setValue("");
    },

    /**
    * on a swipe on a list item the application reverses the completed  
    * value of the record.
    * Call sync on the store to push changes to sencha.io
    * After sync completes call syncCallback.
    */
    toggleTodo: function(dataview, index, target, record, e, options) {
        console.log("swipe?")
        var completed = record.get('completed');
        record.set("completed", !completed);
        var todos = Ext.getStore('todos');
        todos.sync(Ext.bind(this.syncCallback, this));

    },

    /*
    * After the store sync is complete the application needs
    * to notify the user's other devices that the store has changed.
    */
    syncCallback: function() {
        console.log("broadcast update", arguments);
        this.getApplication().sio.getUser(function(user, error) {
            if (user) {
                console.log("user", user);
                user.send({
                    message: "updated"
                },
                function() {
                    console.log("send callback");
                }
                );

            }
        });
    }
});