/**
* Default authentication panel used by Ext.io.Controller when the user needs to login.
*
* Subclass or replace this class ot create a custom user login experience. 
* Ext.io.Controller listens to events generated by this class and will call methods
* where noted.  To work correctly any replacement or sub-class must provide the same interface.
*
*/
if(!Ext.getVersion('extjs')){
Ext.define("Ext.io.ux.ChooseAuth", {
    extend: 'Ext.Container',
    xtype: "sioChooseAuth",
    requires: ["Ext.TitleBar", "Ext.form.Panel", "Ext.form.FieldSet", "Ext.field.Password",  "Ext.field.Email"],
    
    
    
    
    /**
     * @event loginUser
     * Fired when the user has entered their auth credentials.
     * {Ext.io.Controller} listens for this event and will attempt to login 
     * the user with the passed credentials. 
     * @param {Object} auth Key/values given by the user to authenticate with.
     */
     
     /**
      * @event registerUser
      * Fired when the user wants to create a new account.
      * {Ext.io.Controller} listens for this event and will attempt 
      * to registers the user with the passed information.
      * @param {Object} auth Key/values given by the user to register with.
      */
     
    /**
      * @event cancel
      * Fired when the user doesn't want to login.
      * {Ext.io.Controller} listens for this event and will 
      * close the login pannel.
      */
     
    
    config: {
        layout: "fit",
        fullscreen: true,
        
        
        authMethods: [],
        
        control: {
            "button[action=sioCancelChooseLogin]": {
                tap: "doCancelAuth"
            }
        },

 
        items: [
        {
            docked: 'top',
            xtype: 'titlebar',
            title: 'Login',
            items: [
                {
                    text: "cancel",
                    action: "sioCancelChooseLogin"
                }
            ]
        },
        {
            xtype: "panel",
            id: "sioAuthChooser",
            defaults: {
                xtype: 'button',
                width: "80%",
                ui: 'action',
                margin: "10",
                align: "center"
            },
            
            items: [
                {
                  xtype: "panel",
                  html: "Choose Login Type"
                }
            ]
        }
        ]
    },
    
    
    initialize: function(){
        var methods = this.getAuthMethods();
        this.buttonPanel = this.query("#sioAuthChooser")[0];
        if(!methods || methods.length <= 0) {
            //warning?
            return;
        }
        methods.forEach(Ext.bind(this.createButton, this));
    },
    
    createButton: function(method){
        var btn = Ext.create(method.buttonType ? method.buttonType : "Ext.Button", method);
        btn.on("tap", function(button){
            this.doAuth(button,method);
        }, this);
        this.buttonPanel.add(btn);
    },
   
    /**
       * @private
       */
   doCancelAuth: function(button) {
       this.fireEvent("cancel");
   },


    /**
    * @private
    */
    doAuth: function(button, method) {
        this.fireEvent("authMethod", method);
    }
});
}